---
- hosts: osx-template

  vars_files:
  - vars/main.yml

  roles:
  - homebrew

  tasks:

  # Homebrew Taps
  - name: Ensure configured homebrew taps outside Github are installed.
    shell: /usr/local/bin/brew tap {{ item.name }} {{ item.url }}
    with_items: homebrew.taps_out_of_github

  # Homebrew Formulae
  - name: Ensure configured homebrew formulae are installed.
    homebrew: "name={{ item }} state=present"
    with_items: homebrew.formulae

  # Homebrew Casks
  - name: Ensure configured homebrew casks are installed.
    homebrew_cask: "name={{ item }} state=present"
    with_items: homebrew.casks
